parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Domain\:
        resource: '../src/Domain/'
        exclude:
            - '../src/Domain/**/Entity/'
            - '../src/Domain/**/Exception/'

    App\Application\:
        resource: '../src/Application/'
        exclude:
            - '../src/Application/**/DTO/'

    App\Infrastructure\:
        resource: '../src/Infrastructure/'
        exclude:
            - '../src/Infrastructure/**/Persistence/Doctrine/Migrations/'
            - '../src/Infrastructure/**/Http/Controller/'

    # Bindings interfaz → implementación Doctrine
    App\Domain\Betting\Repository\TeamRepositoryInterface:
        class: App\Infrastructure\Betting\Persistence\Doctrine\DoctrineTeamRepository

    App\Domain\Betting\Repository\TeamExternalIdRepositoryInterface:
        class: App\Infrastructure\Betting\Persistence\Doctrine\DoctrineTeamExternalIdRepository


    App\Domain\Betting\Repository\FootballDataProviderInterface:
        class: App\Infrastructure\Betting\Http\Client\FootballDataClient
        arguments:
            $apiKey: '%env(FOOTBALL_DATA_API_KEY)%'

    App\Domain\Betting\Repository\BetRepositoryInterface:
        class: App\Infrastructure\Betting\Persistence\Doctrine\DoctrineBetRepository

    App\Domain\Betting\Repository\TeamBetStatsRepositoryInterface:
        class: App\Infrastructure\Betting\Persistence\Doctrine\DoctrineTeamBetStatsRepository

    _instanceof:
        App\Domain\Betting\Criterion\BetCriterionInterface:
            tags: ['app.bet_criterion']

    App\Application\Betting\Service\BetEvaluatorService:
        arguments:
            $criteria: !tagged_iterator app.bet_criterion

    App\Application\Betting\Service\TomorrowBetsService:
        arguments:
            $criteria: !tagged_iterator app.bet_criterion

    App\Infrastructure\Betting\Http\Controller\BetsController:
        tags: ['controller.service_arguments']
        public: true

    App\Infrastructure\Betting\Http\Controller\BetsHistoryController:
        tags: ['controller.service_arguments']
        public: true

