<?php

declare(strict_types=1);

namespace App\Infrastructure\Shared\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260308184538 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fixture_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, opponent_name VARCHAR(100) NOT NULL, bet_type VARCHAR(20) NOT NULL, status VARCHAR(10) NOT NULL, season VARCHAR(7) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, settled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, team_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FBF0EC9B296CD8AE ON bet (team_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_bet_team_fixture_type ON bet (team_id, fixture_date, bet_type)');
        $this->addSql('CREATE TABLE team_bet_stats (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, bet_type VARCHAR(20) NOT NULL, season VARCHAR(7) NOT NULL, times_bet INT DEFAULT 0 NOT NULL, times_won INT DEFAULT 0 NOT NULL, times_lost INT DEFAULT 0 NOT NULL, team_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CF08D319296CD8AE ON team_bet_stats (team_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_team_bet_stats ON team_bet_stats (team_id, bet_type, season)');
        $this->addSql('ALTER TABLE bet ADD CONSTRAINT FK_FBF0EC9B296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_bet_stats ADD CONSTRAINT FK_CF08D319296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bet DROP CONSTRAINT FK_FBF0EC9B296CD8AE');
        $this->addSql('ALTER TABLE team_bet_stats DROP CONSTRAINT FK_CF08D319296CD8AE');
        $this->addSql('DROP TABLE bet');
        $this->addSql('DROP TABLE team_bet_stats');
    }
}
