<?php

declare(strict_types=1);

namespace App\Infrastructure\Shared\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260306134925 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create team and team_external_id tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE team (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, league VARCHAR(10) NOT NULL, form_last8 VARCHAR(8) DEFAULT NULL, form_last5_home VARCHAR(5) DEFAULT NULL, form_last5_away VARCHAR(5) DEFAULT NULL, over25_home INT DEFAULT 0 NOT NULL, matches_played_home INT DEFAULT 0 NOT NULL, over15_away INT DEFAULT 0 NOT NULL, matches_played_away INT DEFAULT 0 NOT NULL, next_fixture_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, next_fixture_opponent_id INT DEFAULT NULL, next_fixture_is_home BOOLEAN DEFAULT NULL, last_synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE team_external_id (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider VARCHAR(50) NOT NULL, external_id VARCHAR(50) NOT NULL, team_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_744538FD296CD8AE ON team_external_id (team_id)');
        $this->addSql('ALTER TABLE team_external_id ADD CONSTRAINT FK_744538FD296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE team_external_id DROP CONSTRAINT FK_744538FD296CD8AE');
        $this->addSql('DROP TABLE team');
        $this->addSql('DROP TABLE team_external_id');
    }
}
